const ActionList = {
  SESSION: {
    START_SESSION: 'START_SESSION',
    EXIT_SESSION: 'EXIT_SESSION',
  },
  GAME: {
    UPDATE_PLAYERS: 'UPDATE_PLAYERS',
    SUBMIT_CARD: 'SUBMIT_CARD',
    SELECT_CARD: 'SELECT_CARD',
    FLIP_CARDS: 'FLIP_CARDS',
    CLEAR_TABLE: 'RESET_GAME',
    SUBMITTED_CARDS: 'SUBMITTED_CARDS',
  },
};

export default ActionList;
